#!/bin/bash

getPosixOrWindows()
{
  if [ "$OSTYPE" == "linux-gnu" ]
  then
    if grep -q Microsoft /proc/version
    then
      echo "windows"
      return 0
    else
      echo "posix"
      return 0
    fi
  fi
  echo "posix"
  return 0
}

getSystemPath()
{
  local inPath=$1
  local windows=$(getPosixOrWindows)

  if [ "$windows" == "windows" ]
  then
    echo $(wslpath -w $inPath)
  else
    echo $inPath
  fi
}

getDockerExec()
{
  # Detect if we are running in WSL, if so use the Windows binary
  local windows=$(getPosixOrWindows)

  if [ "$windows" == "windows" ]
  then
    echo "docker.exe"
  else
    echo "docker"
  fi
}

getHome()
{
  local windows=$(getPosixOrWindows)

  if [ "$windows" == "windows" ]
  then
    echo "$WINHOME"
  else
    echo "$HOME"
  fi

}
